name: models
description: Models for Alpha Advantage
version: 0.0.1
author: Vyacheslav Ryabinin <ryabinin.v.v@gmail.com>
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.1
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1+3
  json_serializable: ^4.1.1

flutter:
